name: Conventional Labels

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PR based on conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: |
            {
              "feat": "feature",
              "fix": "fix",
              "bug": "bug",
              "docs": "documentation",
              "style": "improvement",
              "refactor": "refactor",
              "perf": "performance",
              "test": "test",
              "build": "build",
              "ci": "ci",
              "chore": "chore",
              "revert": "fix"
            }
          ignored_types: '[]'
